### ISSUE TITLE
Hi Dr. Feng, I have some questions about this reserach.

### ISSUE THREAD

**Issue by LanXiaoPang613** [MrChenFeng/CLIPCleaner_ACMMM2024#1]
Hi Dr. Feng, I have some questions about this reserach. In the table 9 of the appendix A, you compare the performance of CLIP and ALIGN on cifar-10 with IDN. The experimantal results demonstrate the effectiveness of ViT for LNL, but i want to know if the performance of these two models are similar in the scenarios of symmetric or asymmetric noise for CIFAR-10?

**Comment by MrChenFeng** [comment]
Hi Lanxiao, 

I didn't compare these two models on class-dependent noise. I would expect ALIGN will achieve similarly good results as such noise is is easier to distinguish. Btw, it is VLM rather than ViT here :)

Best, 
Chen
